
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Get environment variables or use fallback values
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://jviniubnrvpjycgcdbul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2aW5pdWJucnZwanljZ2NkYnVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NzE1OTIsImV4cCI6MjA1ODM0NzU5Mn0.Pn2yEPHEn32zOONFt1ztlSZGFiMWwWnOoykBaeIYP5E";

// Log connection details for debugging
console.log("Connecting to Supabase at:", SUPABASE_URL);
console.log("API Key exists:", !!SUPABASE_PUBLISHABLE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
